#!/usr/bin/env python3
"""One-time freeze: snapshot the deterministic-verification authority from the
current generated manifests.  Run only when a reviewed decision changes the
verification contract; the resulting authority is committed as a static file and
thereafter verified (never regenerated) by `verify_verification_authority.py`."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MANIFESTS = ROOT / "manifests"
sys.path.insert(0, str(ROOT))

from dal_jcs import canonical_bytes  # noqa: E402
from verify_verification_authority import (  # noqa: E402
    digest,
    expected_oracle_entries,
    semantic_counts,
)


def main() -> None:
    request_schema_path = MANIFESTS / "verification-request_schema_v1.0.json"
    response_schema_path = MANIFESTS / "verification-response_schema_v1.0.json"
    registry = json.loads((MANIFESTS / "verification-registry_v1.0.json").read_text())
    fixtures = json.loads((MANIFESTS / "verification-fixtures_v1.0.json").read_text())
    oracles = json.loads((MANIFESTS / "verification-oracles_v1.0.json").read_text())
    manifest = json.loads((MANIFESTS / "verification-manifest_v1.0.json").read_text())

    entries = expected_oracle_entries(manifest, fixtures, oracles)
    counts = semantic_counts(registry, entries)

    authority = {
        "schema_version": "dal.verification-authority/1.0",
        "authority_version": "1.0",
        "source_boundary": "static-independent-review-authority; never generated by build_verification_manifests.py",
        "frozen_request_schema_sha256": hashlib.sha256(
            request_schema_path.read_bytes()
        ).hexdigest(),
        "frozen_response_schema_sha256": hashlib.sha256(
            response_schema_path.read_bytes()
        ).hexdigest(),
        "frozen_registry_sha256": registry["registry_sha256"],
        "frozen_fixture_catalog_sha256": fixtures["catalog_sha256"],
        "frozen_oracle_catalog_sha256": oracles["catalog_sha256"],
        "frozen_manifest_sha256": manifest["manifest_sha256"],
        "semantic_counts": counts,
        "oracle_entries": entries,
    }
    authority["authority_sha256"] = digest(
        {k: v for k, v in authority.items() if k != "authority_sha256"}
    )
    (MANIFESTS / "verification-authority_v1.0.json").write_text(
        json.dumps(authority, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps({"frozen": True, "semantic_counts": counts}, sort_keys=True))


if __name__ == "__main__":
    main()
