"""finance mcp baseline

Revision ID: 0001_finance_baseline
Revises: none
Create Date: 2026-07-23 05:59:18.072496
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

import personal_agent_core.sqlite


revision: str = '0001_finance_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('redacted_summary', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.Text(), nullable=True),
    sa.Column('event_hash', sa.Text(), nullable=False),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('sequence', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_audit_events_event_id')),
    sa.UniqueConstraint('event_hash', name=op.f('uq_audit_events_event_hash'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_trace_id', ['trace_id'], unique=False)

    op.create_table('duplicate_checks',
    sa.Column('check_id', sa.Text(), nullable=False),
    sa.Column('intent_fingerprint', sa.Text(), nullable=False),
    sa.Column('encrypted_candidate_record_ids', personal_agent_core.sqlite.EncryptedEnvelope(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('expires_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('decided_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.CheckConstraint("(status = 'awaiting_decision') = (decided_at IS NULL)", name=op.f('ck_duplicate_checks_decided_at_matches_status')),
    sa.CheckConstraint("status IN ('awaiting_decision', 'write_anyway', 'dismissed', 'expired')", name=op.f('ck_duplicate_checks_status')),
    sa.PrimaryKeyConstraint('check_id', name=op.f('pk_duplicate_checks'))
    )
    op.create_table('resource_locks',
    sa.Column('lock_key', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('lease_until', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('acquired_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('lock_key', name=op.f('pk_resource_locks'))
    )
    op.create_table('schema_snapshots',
    sa.Column('snapshot_id', sa.Text(), nullable=False),
    sa.Column('ledger_year', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.Text(), nullable=False),
    sa.Column('schema_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('validated_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("status IN ('valid', 'drifted')", name=op.f('ck_schema_snapshots_status')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_schema_snapshots'))
    )
    with op.batch_alter_table('schema_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_schema_snapshots_ledger_year', ['ledger_year'], unique=False)

    op.create_table('tool_executions',
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=False),
    sa.Column('request_fingerprint', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('client_token', sa.Text(), nullable=False),
    sa.Column('encrypted_payload', personal_agent_core.sqlite.EncryptedEnvelope(), nullable=True),
    sa.Column('encrypted_result', personal_agent_core.sqlite.EncryptedEnvelope(), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('recovery_lease_owner', sa.Text(), nullable=True),
    sa.Column('recovery_lease_until', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('updated_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('submitted_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.Column('completed_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.CheckConstraint("state IN ('prepared', 'failed_safe', 'cancelled_pre_submit') OR submitted_at IS NOT NULL", name=op.f('ck_tool_executions_post_submit_states_record_submission_time')),
    sa.CheckConstraint("state IN ('prepared', 'submitting', 'commit_unknown', 'reconciling_same_client_token', 'committed_unverified', 'succeeded', 'failed_safe', 'needs_manual_review', 'cancelled_pre_submit')", name=op.f('ck_tool_executions_state')),
    sa.CheckConstraint('(recovery_lease_owner IS NULL) = (recovery_lease_until IS NULL)', name=op.f('ck_tool_executions_lease_owner_and_expiry_together')),
    sa.CheckConstraint('state_version >= 1', name=op.f('ck_tool_executions_state_version_positive')),
    sa.PrimaryKeyConstraint('idempotency_key', name=op.f('pk_tool_executions')),
    sa.UniqueConstraint('client_token', name=op.f('uq_tool_executions_client_token'))
    )
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.create_index('ix_tool_executions_state', ['state'], unique=False)

    op.create_table('external_receipts',
    sa.Column('receipt_id', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('table_kind', sa.Text(), nullable=False),
    sa.Column('record_id', sa.Text(), nullable=False),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('verified_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.CheckConstraint("table_kind IN ('expense', 'income', 'family_fund')", name=op.f('ck_external_receipts_table_kind')),
    sa.ForeignKeyConstraint(['idempotency_key'], ['tool_executions.idempotency_key'], name=op.f('fk_external_receipts_idempotency_key'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('receipt_id', name=op.f('pk_external_receipts')),
    sa.UniqueConstraint('idempotency_key', 'table_kind', name='idempotency_key_table_kind')
    )
    op.create_table('fx_evidence',
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('base_currency', sa.Text(), nullable=False),
    sa.Column('quote_currency', sa.Text(), nullable=False),
    sa.Column('rate', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('quote_date', sa.Text(), nullable=False),
    sa.Column('fetched_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("provider = 'frankfurter_ecb'", name=op.f('ck_fx_evidence_provider_is_pinned')),
    sa.CheckConstraint("quote_currency = 'CNY'", name=op.f('ck_fx_evidence_quote_is_cny')),
    sa.ForeignKeyConstraint(['idempotency_key'], ['tool_executions.idempotency_key'], name=op.f('fk_fx_evidence_idempotency_key'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_fx_evidence'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fx_evidence')
    op.drop_table('external_receipts')
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_executions_state')

    op.drop_table('tool_executions')
    with op.batch_alter_table('schema_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_schema_snapshots_ledger_year')

    op.drop_table('schema_snapshots')
    op.drop_table('resource_locks')
    op.drop_table('duplicate_checks')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_trace_id')

    op.drop_table('audit_events')
    # ### end Alembic commands ###
