"""The DAL declarative base.

DAL-007 establishes only the independent base: a DAL-specific `MetaData` with
the shared naming convention, so autogenerated migrations stay reviewable and
the DAL schema can never be merged into or confused with another service's
metadata. No tables are declared here yet — the schema is DAL-008's contract
(`DAL-T-DB-CONTRACT-001`), implemented tests-first against the frozen oracles.

Keeping the naming convention identical to the other services is deliberate:
a constraint name that shifts between runs makes a rollback diff impossible to
read, and the convention is the thing that keeps names stable.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

from personal_agent_core.sqlite import NAMING_CONVENTION


class Base(DeclarativeBase):
    """The DAL declarative base, on its own metadata."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
