"""Agent API tables, per technical design 8.1.

This database holds the client-facing projection: devices, requests, operations,
conversations, reviews and the notification outbox. It is deliberately not the
authority on whether money moved. Finance MCP owns external side-effect state,
and technical design 5.2.2 forbids inferring a ledger outcome by comparing
timestamps across the two databases.

Three invariants are expressed as constraints rather than as prose, because
prose does not survive a refactor:

- one client request maps to at most one operation, via a unique
  `(device_id, client_request_id)`;
- an operation's state is drawn from the fixed set in technical design 5.2, and
  `cancel_requested` / `client_detached` are separate flags rather than states,
  so a disconnect can never be recorded as a cancelled write;
- one review card exists per review date.

Each child carries a many-to-one `relationship()`. A `ForeignKey` alone does
not tell the unit of work which row to insert first: SQLAlchemy falls back to
mapper sort order, which is alphabetical, so an `api_requests` insert would be
attempted before the `devices` row it points at.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Final

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
)

from personal_agent.storage.types import EncryptedEnvelope, UtcTimestamp


#: Authoritative operation states. `policy_denied` is a reason code on
#: `failed_safe`, not a state of its own.
OPERATION_STATES: Final[tuple[str, ...]] = (
    "accepted",
    "interpreting",
    "waiting_for_clarification",
    "waiting_for_duplicate_decision",
    "dispatching",
    "source_in_progress",
    "verifying",
    "succeeded",
    "failed_safe",
    "needs_manual_review",
    "cancelled_pre_submit",
)

#: States after which no further transition is allowed.
TERMINAL_OPERATION_STATES: Final[frozenset[str]] = frozenset(
    {"succeeded", "failed_safe", "needs_manual_review", "cancelled_pre_submit"}
)

#: States the recovery scan must reconcile against Finance MCP on startup.
RECOVERABLE_OPERATION_STATES: Final[tuple[str, ...]] = (
    "dispatching",
    "source_in_progress",
    "verifying",
)

DEVICE_STATUSES: Final[tuple[str, ...]] = ("active", "revoked")
REVIEW_STATUSES: Final[tuple[str, ...]] = ("pending", "deferred", "reviewed")

NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}


def _in_set(column: str, values: tuple[str, ...]) -> str:
    joined = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({joined})"


class Base(DeclarativeBase):
    """Declarative base with deterministic constraint names.

    Autogenerated migrations are unusable for rollback review if constraint
    names shift between runs, so the naming convention is fixed here.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Device(Base):
    __tablename__ = "devices"

    device_id: Mapped[str] = mapped_column(Text, primary_key=True)
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    #: P-256 X9.63 uncompressed point, base64url. A public key, not a secret.
    public_key: Mapped[str] = mapped_column(Text, nullable=False)
    device_key_thumbprint: Mapped[str] = mapped_column(Text, nullable=False)
    #: APNs tokens identify a device to a third party, so they are sealed.
    encrypted_push_token: Mapped[dict[str, Any] | None] = mapped_column(
        EncryptedEnvelope, nullable=True
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, default="active")
    scopes: Mapped[str] = mapped_column(Text, nullable=False, default="[]")
    allowed_tools_version: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(
        UtcTimestamp, nullable=True
    )

    __table_args__ = (
        CheckConstraint(_in_set("status", DEVICE_STATUSES), name="status"),
        CheckConstraint(
            "(status = 'active' AND revoked_at IS NULL) "
            "OR (status = 'revoked' AND revoked_at IS NOT NULL)",
            name="revoked_at_matches_status",
        ),
    )


class EnrollmentCode(Base):
    __tablename__ = "enrollment_codes"

    code_hash: Mapped[str] = mapped_column(Text, primary_key=True)
    grants_device_manage: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    created_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(UtcTimestamp, nullable=True)


class AuthChallenge(Base):
    __tablename__ = "auth_challenges"

    challenge_id: Mapped[str] = mapped_column(Text, primary_key=True)
    device_id: Mapped[str] = mapped_column(
        ForeignKey("devices.device_id", ondelete="CASCADE"), nullable=False
    )
    nonce_hash: Mapped[str] = mapped_column(Text, nullable=False)

    failed_attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    created_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)
    consumed_at: Mapped[datetime | None] = mapped_column(
        UtcTimestamp, nullable=True
    )

    device: Mapped["Device"] = relationship()

    __table_args__ = (
        CheckConstraint("failed_attempts >= 0", name="failed_attempts_non_negative"),
        Index("ix_auth_challenges_device_id", "device_id"),
    )


class Conversation(Base):
    __tablename__ = "conversations"

    conversation_id: Mapped[str] = mapped_column(Text, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)
    last_event_at: Mapped[datetime | None] = mapped_column(
        UtcTimestamp, nullable=True
    )


class ConversationEvent(Base):
    """Retained permanently by Henson's decision, always sealed.

    Permanent retention is not permission to feed the archive to a model. Only
    explicit export and deletion are supported in Phase 1.
    """

    __tablename__ = "conversation_events"

    event_id: Mapped[str] = mapped_column(Text, primary_key=True)
    conversation_id: Mapped[str] = mapped_column(
        ForeignKey("conversations.conversation_id", ondelete="CASCADE"),
        nullable=False,
    )
    event_type: Mapped[str] = mapped_column(Text, nullable=False)

    encrypted_content: Mapped[dict[str, Any]] = mapped_column(
        EncryptedEnvelope, nullable=False
    )
    operation_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)

    conversation: Mapped["Conversation"] = relationship()

    __table_args__ = (
        Index("ix_conversation_events_conversation_id", "conversation_id"),
    )


class ApiRequest(Base):
    __tablename__ = "api_requests"

    request_id: Mapped[str] = mapped_column(Text, primary_key=True)
    device_id: Mapped[str] = mapped_column(
        ForeignKey("devices.device_id", ondelete="RESTRICT"), nullable=False
    )
    client_request_id: Mapped[str] = mapped_column(Text, nullable=False)
    request_fingerprint: Mapped[str] = mapped_column(Text, nullable=False)

    encrypted_request_payload: Mapped[dict[str, Any] | None] = mapped_column(
        EncryptedEnvelope, nullable=True
    )
    received_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)

    device: Mapped["Device"] = relationship()

    __table_args__ = (
        # The whole point of client idempotency: the same key from the same
        # device can only ever name one request.
        UniqueConstraint(
            "device_id", "client_request_id", name="device_id_client_request_id"
        ),
    )


class Operation(Base):
    __tablename__ = "operations"

    operation_id: Mapped[str] = mapped_column(Text, primary_key=True)
    request_id: Mapped[str] = mapped_column(
        ForeignKey("api_requests.request_id", ondelete="RESTRICT"),
        nullable=False,
        unique=True,
    )
    trace_id: Mapped[str] = mapped_column(Text, nullable=False)
    #: Same UUIDv4 the client sent; also the Feishu client_token downstream.
    idempotency_key: Mapped[str] = mapped_column(
        Text, nullable=False, unique=True
    )
    tool: Mapped[str | None] = mapped_column(Text, nullable=True)

    api_request: Mapped["ApiRequest"] = relationship()

    state: Mapped[str] = mapped_column(Text, nullable=False)
    #: Compare-and-swap guard so a resumed worker cannot overwrite newer state.
    state_version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1
    )
    failure_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: Kept apart from `state`: a client giving up never means the write did.
    cancel_requested: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    client_detached: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    duplicate_check_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    safe_result: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)

    __table_args__ = (
        CheckConstraint(_in_set("state", OPERATION_STATES), name="state"),
        CheckConstraint("state_version >= 1", name="state_version_positive"),
        Index("ix_operations_state", "state"),
    )


class ConnectorCatalog(Base):
    __tablename__ = "connector_catalog"

    connector_id: Mapped[str] = mapped_column(Text, primary_key=True)
    protocol_version: Mapped[str] = mapped_column(Text, nullable=False)
    capabilities: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    catalog_hash: Mapped[str] = mapped_column(Text, nullable=False)
    health_status: Mapped[str] = mapped_column(Text, nullable=False)
    last_connected_at: Mapped[datetime | None] = mapped_column(
        UtcTimestamp, nullable=True
    )
    last_discovered_at: Mapped[datetime | None] = mapped_column(
        UtcTimestamp, nullable=True
    )


class DailyReview(Base):
    __tablename__ = "daily_reviews"

    review_id: Mapped[str] = mapped_column(Text, primary_key=True)
    #: Unique so catch-up runs cannot create a second card for the same day.
    review_date: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    created_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)
    reviewed_at: Mapped[datetime | None] = mapped_column(
        UtcTimestamp, nullable=True
    )

    __table_args__ = (
        CheckConstraint(_in_set("status", REVIEW_STATUSES), name="status"),
        CheckConstraint(
            "review_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'",
            name="review_date_is_iso",
        ),
    )


class DailyReviewItem(Base):
    """A pointer to an external record, never a copy of its values.

    The card must show what Feishu holds now, so that a manual correction on the
    computer is visible immediately. Caching amounts here would show stale ones.
    """

    __tablename__ = "daily_review_items"

    item_id: Mapped[str] = mapped_column(Text, primary_key=True)
    review_id: Mapped[str] = mapped_column(
        ForeignKey("daily_reviews.review_id", ondelete="CASCADE"), nullable=False
    )
    tool: Mapped[str] = mapped_column(Text, nullable=False)
    record_id: Mapped[str] = mapped_column(Text, nullable=False)

    review: Mapped["DailyReview"] = relationship()
    committed_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)

    __table_args__ = (
        UniqueConstraint("review_id", "record_id", name="review_id_record_id"),
    )


class NotificationOutbox(Base):
    __tablename__ = "notification_outbox"

    event_id: Mapped[str] = mapped_column(Text, primary_key=True)
    device_id: Mapped[str] = mapped_column(
        ForeignKey("devices.device_id", ondelete="CASCADE"), nullable=False
    )
    review_id: Mapped[str | None] = mapped_column(Text, nullable=True)

    device: Mapped["Device"] = relationship()
    #: APNs accepting a push is not the user having seen it.
    provider_status: Mapped[str] = mapped_column(Text, nullable=False)
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    next_attempt_at: Mapped[datetime | None] = mapped_column(
        UtcTimestamp, nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)

    __table_args__ = (
        CheckConstraint("attempts >= 0", name="attempts_non_negative"),
    )


class DeletionManifest(Base):
    """What a restore must re-apply so deleted data does not come back.

    The object id is sealed: a manifest that names conversations in plaintext
    would leak exactly what the user asked to remove.
    """

    __tablename__ = "deletion_manifest"

    entry_id: Mapped[str] = mapped_column(Text, primary_key=True)
    object_type: Mapped[str] = mapped_column(Text, nullable=False)
    encrypted_object_id: Mapped[dict[str, Any]] = mapped_column(
        EncryptedEnvelope, nullable=False
    )
    deleted_at: Mapped[datetime] = mapped_column(UtcTimestamp, nullable=False)
    backup_expiry_after: Mapped[datetime | None] = mapped_column(
        UtcTimestamp, nullable=True
    )
