"""core spine: the DAL workflow database's first schema

`DAL-008`, decision D1(B). This revision carries the spine the five
`DAL-T-DB-CONTRACT-001` oracles exercise, plus the one aggregate they act on:

- `features` — the CAS root, whose column set is fixed by contract §3.2.1
  because `state_sha256` is recomputed from exactly these fields;
- `operation_receipts` — the idempotency ledger, constrained so only `APPLIED`
  can be stored;
- `migration_receipts` — when the schema moved, from where, and whether the
  integrity check that followed passed;
- `audit_events` + `audit_chain_anchor` — the hash-chained trail and the
  independent tail witness that detects truncation;
- `events` (sealed payload column) + `event_quarantine` + `operation_events`;
- `outbox_events` and `retention_tombstones`.

The remaining §3.1 entities are deliberately absent: they land in `0002`/`0003`
with the tests that consume them, so no field is frozen before something
checks it.

The four triggers at the end are the part autogenerate cannot see, and the
part that matters most: they are how `merged`/`deployed` stay un-cancellable,
how a terminal feature stays terminal, and how the audit trail stays
append-only when the code that writes it is wrong.

Revision ID: 0001
Revises: none
Create Date: 2026-08-10
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

import personal_agent_core.sqlite

from personal_agent_dal.storage.models import TRIGGER_STATEMENTS


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_chain_anchor',
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('tail_hash', sa.Text(), nullable=False),
    sa.Column('updated_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint('anchor_id = 1', name=op.f('ck_audit_chain_anchor_singleton')),
    sa.PrimaryKeyConstraint('anchor_id', name=op.f('pk_audit_chain_anchor'))
    )
    op.create_table('audit_events',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('redacted_summary', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.Text(), nullable=True),
    sa.Column('event_hash', sa.Text(), nullable=False),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('sequence', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('event_hash', name=op.f('uq_audit_events_event_hash')),
    sa.UniqueConstraint('event_id', name=op.f('uq_audit_events_event_id'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_trace_id', ['trace_id'], unique=False)

    op.create_table('event_quarantine',
    sa.Column('quarantine_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observed_event_type', sa.Text(), nullable=False),
    sa.Column('envelope_sha256', sa.Text(), nullable=False),
    sa.Column('received_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('alerted_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.CheckConstraint("(length(envelope_sha256) = 64 AND envelope_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_event_quarantine_envelope_sha256_hex')),
    sa.PrimaryKeyConstraint('quarantine_id', name=op.f('pk_event_quarantine'))
    )
    op.create_table('events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Text(), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Text(), nullable=True),
    sa.Column('causation_id', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('occurred_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('encrypted_payload', personal_agent_core.sqlite.EncryptedEnvelope(), nullable=True),
    sa.Column('payload_sha256', sa.Text(), nullable=False),
    sa.CheckConstraint("(length(payload_sha256) = 64 AND payload_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_events_payload_sha256_hex')),
    sa.CheckConstraint("actor_type IN ('service', 'human', 'worker')", name=op.f('ck_events_actor_type')),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_events')),
    sa.UniqueConstraint('aggregate_type', 'aggregate_id', 'aggregate_version', 'event_type', name='aggregate_version_event_type'),
    sa.UniqueConstraint('event_id', name=op.f('uq_events_event_id'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_occurred_at', ['occurred_at'], unique=False)

    op.create_table('features',
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('checkpoint_state', sa.Text(), nullable=True),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('reason_owner', sa.Text(), nullable=True),
    sa.Column('plan_version', sa.Integer(), nullable=True),
    sa.Column('artifact_sha256', sa.Text(), nullable=True),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('base_sha', sa.Text(), nullable=False),
    sa.Column('result_sha', sa.Text(), nullable=True),
    sa.Column('last_verified_sha', sa.Text(), nullable=True),
    sa.Column('decision_frontier_version', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('capability_epoch', sa.Integer(), nullable=False),
    sa.Column('external_effect_inventory_sha256', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('updated_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("(artifact_sha256 IS NULL OR (length(artifact_sha256) = 64 AND artifact_sha256 NOT GLOB '*[^0-9a-f]*'))", name=op.f('ck_features_artifact_sha256_hex')),
    sa.CheckConstraint("(last_verified_sha IS NULL OR (length(last_verified_sha) = 40 AND last_verified_sha NOT GLOB '*[^0-9a-f]*'))", name=op.f('ck_features_last_verified_sha_hex')),
    sa.CheckConstraint("(length(base_sha) = 40 AND base_sha NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_features_base_sha_hex')),
    sa.CheckConstraint("(length(external_effect_inventory_sha256) = 64 AND external_effect_inventory_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_features_inventory_sha256_hex')),
    sa.CheckConstraint("(result_sha IS NULL OR (length(result_sha) = 40 AND result_sha NOT GLOB '*[^0-9a-f]*'))", name=op.f('ck_features_result_sha_hex')),
    sa.CheckConstraint("NOT (state IN ('blocked_requirement', 'blocked_usage', 'blocked_auth', 'blocked_test', 'blocked_external_prerequisite', 'blocked_unknown', 'needs_human', 'paused')) OR checkpoint_state IS NOT NULL", name=op.f('ck_features_checkpoint_present_when_stopped')),
    sa.CheckConstraint("checkpoint_state IS NULL OR checkpoint_state NOT IN ('completed', 'cancelled')", name=op.f('ck_features_checkpoint_is_not_terminal')),
    sa.CheckConstraint("reason_code IS NULL OR reason_code IN ('REQUIREMENT_MISSING', 'USAGE_LIMIT', 'AUTH_REQUIRED', 'TEST_BLOCKED', 'EXTERNAL_PREREQUISITE', 'TRANSIENT_RETRY_EXHAUSTED', 'PROVIDER_CONTRACT_FAILURE', 'POLICY_FAILURE', 'BUDGET_LIMIT', 'REVIEW_LOOP_LIMIT', 'GIT_CONFLICT', 'STATE_DRIFT', 'POST_EFFECT_EXCEPTION', 'RECOVERY_REQUIRED', 'UNKNOWN_NO_EXTERNAL_INTENT', 'EXTERNAL_RESULT_UNKNOWN', 'USER_PAUSE', 'RECOVERY_READBACK_UNKNOWN', 'RECOVERY_POLICY_STALE', 'RECOVERY_EFFECT_UNKNOWN')", name=op.f('ck_features_reason_code')),
    sa.CheckConstraint("reason_owner IS NULL OR reason_owner IN ('feature', 'recovery_case')", name=op.f('ck_features_reason_owner')),
    sa.CheckConstraint("state IN ('intake', 'planning', 'awaiting_plan_review', 'approved', 'coding', 'verifying', 'reviewing', 'fixing', 'verified', 'awaiting_merge', 'merged', 'deployed', 'completed', 'blocked_requirement', 'blocked_usage', 'blocked_auth', 'blocked_test', 'blocked_external_prerequisite', 'blocked_unknown', 'reconciliation_required', 'needs_human', 'paused', 'cancelled')", name=op.f('ck_features_state')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_features_version_positive')),
    sa.PrimaryKeyConstraint('feature_id', name=op.f('pk_features'))
    )
    op.create_table('migration_receipts',
    sa.Column('migration_receipt_id', sa.Text(), nullable=False),
    sa.Column('from_revision', sa.Text(), nullable=True),
    sa.Column('to_revision', sa.Text(), nullable=False),
    sa.Column('applied_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('applied_by', sa.Text(), nullable=False),
    sa.Column('integrity_check_result', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('migration_receipt_id', name=op.f('pk_migration_receipts'))
    )
    with op.batch_alter_table('migration_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_migration_receipts_applied_at', ['applied_at'], unique=False)

    op.create_table('operation_events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('operation_id', sa.Text(), nullable=False),
    sa.Column('occurred_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.CheckConstraint("event_type IN ('database.migrated', 'database.retention_applied', 'database.encrypted_roundtrip')", name=op.f('ck_operation_events_event_type')),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_operation_events')),
    sa.UniqueConstraint('operation_event_id', name=op.f('uq_operation_events_operation_event_id'))
    )
    op.create_table('operation_receipts',
    sa.Column('operation_id', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('operation_spec_id', sa.Text(), nullable=False),
    sa.Column('command_type', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('evidence_source_type', sa.Text(), nullable=False),
    sa.Column('receipt_code', sa.Text(), nullable=False),
    sa.Column('receipt_schema_version', sa.Text(), nullable=False),
    sa.Column('request_payload_sha256', sa.Text(), nullable=False),
    sa.Column('response_payload_sha256', sa.Text(), nullable=True),
    sa.Column('recorded_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("(length(request_payload_sha256) = 64 AND request_payload_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_operation_receipts_request_payload_sha256_hex')),
    sa.CheckConstraint("(response_payload_sha256 IS NULL OR (length(response_payload_sha256) = 64 AND response_payload_sha256 NOT GLOB '*[^0-9a-f]*'))", name=op.f('ck_operation_receipts_response_payload_sha256_hex')),
    sa.CheckConstraint("receipt_code = 'APPLIED'", name=op.f('ck_operation_receipts_only_applied_persists')),
    sa.PrimaryKeyConstraint('operation_id', name=op.f('pk_operation_receipts')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_operation_receipts_idempotency_key'))
    )
    op.create_table('outbox_events',
    sa.Column('outbox_id', sa.Text(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Text(), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('payload_sha256', sa.Text(), nullable=False),
    sa.Column('delivery_state', sa.Text(), nullable=False),
    sa.Column('available_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("delivery_state IN ('pending', 'delivering', 'delivered', 'retry_wait', 'dead_letter', 'cancelled')", name=op.f('ck_outbox_events_delivery_state')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_outbox_events_attempt_count_non_negative')),
    sa.PrimaryKeyConstraint('outbox_id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('aggregate_type', 'aggregate_id', 'aggregate_version', 'topic', name='aggregate_version_topic')
    )
    op.create_table('retention_tombstones',
    sa.Column('tombstone_id', sa.Text(), nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('sealed_id', sa.Text(), nullable=False),
    sa.Column('cutoff', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('executed_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('operation_id', sa.Text(), nullable=False),
    sa.CheckConstraint("(length(sealed_id) = 64 AND sealed_id NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_retention_tombstones_sealed_id_hex')),
    sa.ForeignKeyConstraint(['operation_id'], ['operation_receipts.operation_id'], name=op.f('fk_retention_tombstones_operation_id')),
    sa.PrimaryKeyConstraint('tombstone_id', name=op.f('pk_retention_tombstones')),
    sa.UniqueConstraint('table_name', 'sealed_id', name='table_name_sealed_id')
    )
    # ### end Alembic commands ###

    # Triggers are shared with `create_all` through one set of statements, so a
    # migrated database and a metadata-built one refuse exactly the same things.
    for _name, statement in TRIGGER_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    for name, _statement in reversed(TRIGGER_STATEMENTS):
        op.execute(f"DROP TRIGGER IF EXISTS {name}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retention_tombstones')
    op.drop_table('outbox_events')
    op.drop_table('operation_receipts')
    op.drop_table('operation_events')
    with op.batch_alter_table('migration_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_migration_receipts_applied_at')

    op.drop_table('migration_receipts')
    op.drop_table('features')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_occurred_at')

    op.drop_table('events')
    op.drop_table('event_quarantine')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_trace_id')

    op.drop_table('audit_events')
    op.drop_table('audit_chain_anchor')
    # ### end Alembic commands ###
