"""state machine: the entities DAL-009's transitions write to

`DAL-009`. The table set is derived, not designed: it is exactly the union of
`atomic_write_set` members across the 254 registry specs reachable at G1.
Twelve tables — transition receipts, decisions and their dock projections,
approvals and their action receipts, capabilities, leases, external effects,
recovery cases and their source effects, evidence records, impact reports.

This re-cuts the `0002` boundary set out under decision D1(B), which had
guessed at plan/task/run/job. Those are still absent because nothing tests them
yet; what landed here is what the state machine's own tests consume. That the
boundary moved is the split working as intended rather than a deviation from
it.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-10
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

import personal_agent_core.sqlite


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('approval_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('decision_id', sa.Text(), nullable=True),
    sa.Column('decision_version', sa.Integer(), nullable=True),
    sa.Column('expected_feature_version', sa.Integer(), nullable=False),
    sa.Column('expected_state', sa.Text(), nullable=False),
    sa.Column('state_sha256', sa.Text(), nullable=True),
    sa.Column('artifact_sha256', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('valid_from', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('expires_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('replay_policy', sa.Text(), nullable=False),
    sa.Column('consumed_by_command_id', sa.Text(), nullable=True),
    sa.Column('consumed_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.Column('recorded_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("replay_policy = 'consume_once'", name=op.f('ck_approvals_replay_policy')),
    sa.CheckConstraint('(consumed_by_command_id IS NULL) = (consumed_at IS NULL)', name=op.f('ck_approvals_consumption_is_all_or_nothing')),
    sa.PrimaryKeyConstraint('approval_id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_approvals_idempotency_key'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index('ix_approvals_feature_id', ['feature_id'], unique=False)

    op.create_table('capabilities',
    sa.Column('capability_id', sa.Text(), nullable=False),
    sa.Column('approval_id', sa.Text(), nullable=True),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('expires_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses_consumed', sa.Integer(), nullable=False),
    sa.Column('revoked_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint('uses_consumed >= 0 AND uses_consumed <= max_uses', name=op.f('ck_capabilities_uses_within_max')),
    sa.PrimaryKeyConstraint('capability_id', name=op.f('pk_capabilities'))
    )
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.create_index('ix_capabilities_feature_id', ['feature_id'], unique=False)

    op.create_table('decisions',
    sa.Column('decision_id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('decision_version', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('artifact_sha256', sa.Text(), nullable=True),
    sa.Column('state_sha256', sa.Text(), nullable=True),
    sa.Column('is_incident', sa.Boolean(), nullable=False),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('updated_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'resolved', 'consumed', 'superseded')", name=op.f('ck_decisions_status')),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decisions_feature_id', ['feature_id'], unique=False)

    op.create_table('evidence_records',
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('subject_aggregate_type', sa.Text(), nullable=False),
    sa.Column('subject_aggregate_id', sa.Text(), nullable=False),
    sa.Column('evidence_schema_version', sa.Text(), nullable=False),
    sa.Column('payload_sha256', sa.Text(), nullable=False),
    sa.Column('protected_ref', sa.Text(), nullable=True),
    sa.Column('recorded_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("(length(payload_sha256) = 64 AND payload_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_evidence_records_payload_sha256_hex')),
    sa.CheckConstraint("kind IN ('evidence', 'authoritative_receipt', 'authoritative_post_read')", name=op.f('ck_evidence_records_kind')),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence_records'))
    )
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_records_subject', ['subject_aggregate_type', 'subject_aggregate_id'], unique=False)

    op.create_table('external_effects',
    sa.Column('effect_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('owner_aggregate_type', sa.Text(), nullable=False),
    sa.Column('owner_aggregate_id', sa.Text(), nullable=False),
    sa.Column('effect_scope_key', sa.Text(), nullable=False),
    sa.Column('remote_idempotency_key', sa.Text(), nullable=False),
    sa.Column('target_fingerprint', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Text(), nullable=True),
    sa.Column('executor_epoch', sa.Integer(), nullable=True),
    sa.Column('claim_expires_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.Column('capability_id', sa.Text(), nullable=True),
    sa.Column('capability_epoch', sa.Integer(), nullable=True),
    sa.Column('receipt_refs_sha256', sa.Text(), nullable=True),
    sa.Column('post_read_refs_sha256', sa.Text(), nullable=True),
    sa.Column('impact_sha256', sa.Text(), nullable=True),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('updated_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("origin <> 'out_of_band_human' OR (executor_id IS NULL AND executor_epoch IS NULL AND claim_expires_at IS NULL AND state = 'confirmed_completed')", name=op.f('ck_external_effects_observed_effects_have_no_executor')),
    sa.CheckConstraint("origin IN ('dal_dispatched', 'out_of_band_human')", name=op.f('ck_external_effects_origin')),
    sa.CheckConstraint("owner_aggregate_type IN ('feature', 'recovery_case')", name=op.f('ck_external_effects_owner_aggregate_type')),
    sa.CheckConstraint("state IN ('intent_recorded', 'claimed', 'dispatch_started', 'confirmed_completed', 'confirmed_not_executed', 'unknown', 'reconciling')", name=op.f('ck_external_effects_state')),
    sa.PrimaryKeyConstraint('effect_id', name=op.f('pk_external_effects')),
    sa.UniqueConstraint('effect_scope_key', 'remote_idempotency_key', name='scope_key_remote_key')
    )
    with op.batch_alter_table('external_effects', schema=None) as batch_op:
        batch_op.create_index('ix_external_effects_owner', ['owner_aggregate_type', 'owner_aggregate_id'], unique=False)

    op.create_table('impact_reports',
    sa.Column('impact_id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('impact_sha256', sa.Text(), nullable=False),
    sa.Column('effect_inventory_sha256', sa.Text(), nullable=False),
    sa.Column('recorded_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("(length(impact_sha256) = 64 AND impact_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_impact_reports_impact_sha256_hex')),
    sa.CheckConstraint("kind IN ('impact', 'impact_report')", name=op.f('ck_impact_reports_kind')),
    sa.PrimaryKeyConstraint('impact_id', name=op.f('pk_impact_reports'))
    )
    with op.batch_alter_table('impact_reports', schema=None) as batch_op:
        batch_op.create_index('ix_impact_reports_feature_id', ['feature_id'], unique=False)

    op.create_table('leases',
    sa.Column('lease_id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('expires_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('heartbeat_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.Column('revoked_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=True),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('lease_id', name=op.f('pk_leases')),
    sa.UniqueConstraint('job_id', 'epoch', name='job_id_epoch')
    )
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.create_index('ix_leases_feature_id', ['feature_id'], unique=False)

    op.create_table('recovery_cases',
    sa.Column('recovery_case_id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('proposal_sha256', sa.Text(), nullable=True),
    sa.Column('impact_sha256', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.Text(), nullable=True),
    sa.Column('execution_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('updated_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("reason_code IS NULL OR reason_code IN ('RECOVERY_READBACK_UNKNOWN', 'RECOVERY_POLICY_STALE', 'RECOVERY_EFFECT_UNKNOWN')", name=op.f('ck_recovery_cases_reason_code')),
    sa.CheckConstraint("state IN ('investigating', 'awaiting_decision', 'approved', 'executing', 'verifying', 'verified', 'blocked', 'cancelled')", name=op.f('ck_recovery_cases_state')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_recovery_cases_version_positive')),
    sa.PrimaryKeyConstraint('recovery_case_id', name=op.f('pk_recovery_cases'))
    )
    with op.batch_alter_table('recovery_cases', schema=None) as batch_op:
        batch_op.create_index('ix_recovery_cases_feature_id', ['feature_id'], unique=False)

    op.create_table('transition_receipts',
    sa.Column('receipt_id', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Text(), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Text(), nullable=False),
    sa.Column('command_type', sa.Text(), nullable=False),
    sa.Column('from_state', sa.Text(), nullable=True),
    sa.Column('to_state', sa.Text(), nullable=False),
    sa.Column('receipt_code', sa.Text(), nullable=False),
    sa.Column('receipt_schema_version', sa.Text(), nullable=False),
    sa.Column('request_payload_sha256', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=True),
    sa.Column('recorded_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint("(length(request_payload_sha256) = 64 AND request_payload_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_transition_receipts_request_payload_sha256_hex')),
    sa.CheckConstraint("aggregate_type IN ('feature', 'recovery_case', 'external_effect')", name=op.f('ck_transition_receipts_aggregate_type')),
    sa.CheckConstraint("receipt_code = 'APPLIED'", name=op.f('ck_transition_receipts_only_applied_persists')),
    sa.PrimaryKeyConstraint('receipt_id', name=op.f('pk_transition_receipts')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_transition_receipts_idempotency_key'))
    )
    with op.batch_alter_table('transition_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_transition_receipts_aggregate', ['aggregate_type', 'aggregate_id'], unique=False)

    op.create_table('approval_action_receipts',
    sa.Column('receipt_id', sa.Text(), nullable=False),
    sa.Column('approval_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('decision_id', sa.Text(), nullable=True),
    sa.Column('decision_version', sa.Integer(), nullable=True),
    sa.Column('consumed_state_sha256', sa.Text(), nullable=True),
    sa.Column('repository_id', sa.Text(), nullable=True),
    sa.Column('pull_request_id', sa.Text(), nullable=True),
    sa.Column('head_sha', sa.Text(), nullable=True),
    sa.Column('result_sha', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('valid_from', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('expires_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('consumed_by_command_id', sa.Text(), nullable=False),
    sa.Column('consume_event_id', sa.Text(), nullable=False),
    sa.Column('recorded_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.Column('receipt_sha256', sa.Text(), nullable=False),
    sa.CheckConstraint("(length(receipt_sha256) = 64 AND receipt_sha256 NOT GLOB '*[^0-9a-f]*')", name=op.f('ck_approval_action_receipts_receipt_sha256_hex')),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.approval_id'], name=op.f('fk_approval_action_receipts_approval_id')),
    sa.PrimaryKeyConstraint('receipt_id', name=op.f('pk_approval_action_receipts')),
    sa.UniqueConstraint('approval_id', name=op.f('uq_approval_action_receipts_approval_id')),
    sa.UniqueConstraint('consume_event_id', name=op.f('uq_approval_action_receipts_consume_event_id'))
    )
    op.create_table('decision_card_projections',
    sa.Column('projection_id', sa.Text(), nullable=False),
    sa.Column('decision_id', sa.Text(), nullable=False),
    sa.Column('decision_version', sa.Integer(), nullable=False),
    sa.Column('actionable', sa.Boolean(), nullable=False),
    sa.Column('display_state', sa.Text(), nullable=False),
    sa.Column('dock_rank', sa.Integer(), nullable=False),
    sa.Column('created_at', personal_agent_core.sqlite.UtcTimestamp(), nullable=False),
    sa.CheckConstraint('dock_rank BETWEEN 0 AND 4', name=op.f('ck_decision_card_projections_dock_rank')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], name=op.f('fk_decision_card_projections_decision_id')),
    sa.PrimaryKeyConstraint('projection_id', name=op.f('pk_decision_card_projections')),
    sa.UniqueConstraint('decision_id', 'decision_version', name='decision_id_version')
    )
    op.create_table('recovery_case_source_effects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recovery_case_id', sa.Text(), nullable=False),
    sa.Column('effect_id', sa.Text(), nullable=False),
    sa.Column('effect_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.recovery_case_id'], name=op.f('fk_recovery_case_source_effects_recovery_case_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_case_source_effects')),
    sa.UniqueConstraint('recovery_case_id', 'effect_id', name='case_effect')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_case_source_effects')
    op.drop_table('decision_card_projections')
    op.drop_table('approval_action_receipts')
    with op.batch_alter_table('transition_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_transition_receipts_aggregate')

    op.drop_table('transition_receipts')
    with op.batch_alter_table('recovery_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_recovery_cases_feature_id')

    op.drop_table('recovery_cases')
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_index('ix_leases_feature_id')

    op.drop_table('leases')
    with op.batch_alter_table('impact_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_impact_reports_feature_id')

    op.drop_table('impact_reports')
    with op.batch_alter_table('external_effects', schema=None) as batch_op:
        batch_op.drop_index('ix_external_effects_owner')

    op.drop_table('external_effects')
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_records_subject')

    op.drop_table('evidence_records')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_decisions_feature_id')

    op.drop_table('decisions')
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.drop_index('ix_capabilities_feature_id')

    op.drop_table('capabilities')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_approvals_feature_id')

    op.drop_table('approvals')
    # ### end Alembic commands ###
