#!/usr/bin/env python3
"""Generate per-variant Wave 3 machine-artifact rebuild receipts.

Wave 3 §9 item 1 (frozen contract package `docs/dal/DAL021-024_合同冻结包_v0.1.md`
§9) requires the frozen oracle/authority artifacts and the test-manifest
extension rows to be regenerated by ``build_contract_manifests.py`` and bound
per variant. The manifest v1.2 freeze already reserved the rows and the
generator already emits them, so what was still missing is the per-variant
proof that a fresh deterministic rebuild reproduces the frozen bytes and that
every authority covers them.

This generator produces one ``dal.artifact-rebuild-receipt/1.0`` per Wave 3
variant (14 variants: PROVIDER-CONTRACT x8, REVIEW-INDEP x5, INJECTION
provider_output) under ``docs/evidence/artifact-receipts/``. Each receipt
records the recomputed fixture/oracle content hashes, the manifest row digest,
the authority coverage of that variant, the zero-drift rebuild evidence, and
the generator commit the rebuild ran against.

It is deliberately NOT a ``dal.test-receipt/1.0``: that schema means
"implementation executed and passed against the frozen oracle" (§9 item 3).
Binding the artifact stage to that semantics would silently claim G3/G4
implementation, which has not happened and is not authorised.

Fail-closed: the generator refuses to write anything unless the rebuild is
byte-identical (git snapshot compare), all four authorities verify, and every
receipt's recomputed hashes match the manifest row. No truncation, no repair.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = REPO_ROOT / "scripts"

if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tests.dal.contract_loader import FrozenContracts, content_hash  # noqa: E402

RECEIPT_SCHEMA = "dal.artifact-rebuild-receipt/1.0"
GENERATOR = "docs/dal/build_contract_manifests.py"
VERIFIER = "scripts/verify_dal_artifact_receipts.py"
RECEIPTS_DIR = REPO_ROOT / "docs" / "evidence" / "artifact-receipts"
MANIFESTS_DIR = REPO_ROOT / "docs" / "dal" / "manifests"

#: The exact Wave 3 §7 variant set the freeze package reserved in manifest v1.2.
WAVE3_VARIANTS: tuple[tuple[str, str], ...] = (
    ("DAL-T-PROVIDER-CONTRACT-001", "empty"),
    ("DAL-T-PROVIDER-CONTRACT-001", "multi_tool"),
    ("DAL-T-PROVIDER-CONTRACT-001", "prose_tool"),
    ("DAL-T-PROVIDER-CONTRACT-001", "malformed_args"),
    ("DAL-T-PROVIDER-CONTRACT-001", "half_stream"),
    ("DAL-T-PROVIDER-CONTRACT-001", "multi_final"),
    ("DAL-T-PROVIDER-CONTRACT-001", "multi_turn"),
    ("DAL-T-PROVIDER-CONTRACT-001", "context_drift"),
    ("DAL-T-REVIEW-INDEP-001", "same_session"),
    ("DAL-T-REVIEW-INDEP-001", "same_context"),
    ("DAL-T-REVIEW-INDEP-001", "same_independence_key"),
    ("DAL-T-REVIEW-INDEP-001", "synthetic_fresh"),
    ("DAL-T-REVIEW-INDEP-001", "live_fresh"),
    ("DAL-T-INJECTION-001", "provider_output"),
)

#: Files one rebuild touches, compared against the pre-rebuild git snapshot.
REBUILD_SCOPE: tuple[str, ...] = (
    "docs/dal/manifests/transition-spec-registry_v1.0.json",
    "docs/dal/manifests/evidence-schema-registry_v1.0.json",
    "docs/dal/manifests/guard-predicate-registry_v1.0.json",
    "docs/dal/manifests/operation-spec-registry_v1.0.json",
    "docs/dal/manifests/test-fixtures_v1.0.json",
    "docs/dal/manifests/test-oracles_v1.0.json",
    "docs/dal/manifests/test-manifest_v1.2.json",
    "docs/dal/manifests/transition-oracle-authority_v1.0.json",
    "docs/dal/manifests/operation-oracle-authority_v1.0.json",
    "docs/dal/manifests/test-manifest-authority_v1.0.json",
    "docs/dal/manifests/eval-schema-authority_v1.0.json",
    "docs/dal/manifests/eval-run-manifest_schema_v1.0.json",
    "docs/dal/manifests/codex-adapter-request_schema_v1.0.json",
    "docs/dal/manifests/codex-input-manifest_schema_v1.0.json",
    "docs/dal/manifests/codex-adapter-response_schema_v1.0.json",
    "docs/dal/manifests/codex-redacted-log_schema_v1.0.json",
    "docs/dal/manifests/plan-artifact_schema_v1.0.json",
    "docs/dal/manifests/review-findings_schema_v1.0.json",
    "docs/dal/manifests/post-fix-verdict_schema_v1.0.json",
    "docs/dal/manifests/reviewer-session-binding_schema_v1.0.json",
)

RECEIPT_FIELDS: tuple[str, ...] = (
    "schema_version",
    "manifest_sha256",
    "test_id",
    "variant_id",
    "run_gate",
    "owner_tasks_sha256",
    "fixture_ref",
    "fixture_sha256",
    "oracle_id",
    "oracle_sha256",
    "manifest_row_sha256",
    "authority_coverage",
    "rebuild",
    "implementation_sha",
    "implementation_paths",
    "environment",
    "environment_digest",
    "status",
    "recorded_at",
)


def _sha256(value: Any) -> str:
    """JSON-sorted digest; only for values outside the JCS content-hash regime."""
    return hashlib.sha256(
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def _git(*args: str) -> str:
    process = subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        capture_output=True,
        text=True,
    )
    if process.returncode != 0:
        raise RuntimeError(
            f"git {' '.join(args)} failed: {process.stderr.strip()}"
        )
    return process.stdout.strip()


def _file_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _snapshot_manifest_files() -> dict[str, str]:
    """Digest every in-scope frozen file before the rebuild runs."""
    snapshot: dict[str, str] = {}
    for name in REBUILD_SCOPE:
        path = REPO_ROOT / name
        if not path.exists():
            raise FileNotFoundError(f"frozen artifact missing before rebuild: {name}")
        snapshot[name] = _file_digest(path)
    return snapshot


def _run_rebuild() -> None:
    """Run the frozen generator; its own authority checks must pass."""
    process = subprocess.run(
        [sys.executable, str(REPO_ROOT / GENERATOR)],
        capture_output=True,
        text=True,
    )
    if process.returncode != 0:
        raise RuntimeError(
            "build_contract_manifests.py failed; refusing to write receipts:\n"
            + process.stdout
            + process.stderr
        )


def _assert_zero_drift(snapshot: dict[str, str]) -> None:
    for name, before in snapshot.items():
        after = _file_digest(REPO_ROOT / name)
        if after != before:
            raise RuntimeError(
                "rebuild drifted from the frozen bytes; refusing to write receipts: "
                f"{name} changed"
            )


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _authority_coverage(oracle_id: str) -> dict[str, bool]:
    """Which frozen authority carries this oracle; fail closed if none."""
    transition = _load(MANIFESTS_DIR / "transition-oracle-authority_v1.0.json")
    operation = _load(MANIFESTS_DIR / "operation-oracle-authority_v1.0.json")
    manifest_authority = _load(MANIFESTS_DIR / "test-manifest-authority_v1.0.json")
    fixture_catalog = _load(MANIFESTS_DIR / "test-fixtures_v1.0.json")
    oracle_catalog = _load(MANIFESTS_DIR / "test-oracles_v1.0.json")

    coverage = {
        "transition_oracle_authority": oracle_id in transition["entries"],
        "operation_oracle_authority": oracle_id in operation["entries"],
        "test_manifest_authority": any(
            row["oracle_id"] == oracle_id
            for row in manifest_authority["manifest_rows"].values()
        ),
        "test_manifest_row_present": oracle_id in oracle_catalog["oracles"],
        "fixture_catalog_entry_present": None,  # filled by caller via fixture_ref
    }
    return coverage


def _fixture_in_authority(fixture_ref: str) -> bool:
    manifest_authority = _load(MANIFESTS_DIR / "test-manifest-authority_v1.0.json")
    return any(
        row["fixture_ref"] == fixture_ref
        for row in manifest_authority["manifest_rows"].values()
    )


def _build_receipt(
    row: dict[str, Any],
    *,
    manifest_sha256: str,
    rebuild_evidence: dict[str, Any],
    implementation_sha: str,
    implementation_paths: list[str],
    recorded_at: str,
) -> dict[str, Any]:
    """Restate the frozen manifest row itself; no field is reconstructed.

    Every row-derived field below is copied verbatim from the frozen row, and
    ``manifest_row_sha256`` digests that exact row with the project's JCS
    content hash. The cross-check against the independently recomputed
    contract binding happens in :func:`_assert_receipt_consistent`.
    """
    coverage = _authority_coverage(row["oracle_id"])
    coverage["fixture_catalog_entry_present"] = _fixture_in_authority(
        row["fixture_ref"]
    )

    environment = {
        "architecture": platform.machine(),
        "os": sys.platform,
        "python_version": platform.python_version(),
        "runner": "scripts/generate_dal_wave3_artifact_receipts.py",
    }

    return {
        "schema_version": RECEIPT_SCHEMA,
        "manifest_sha256": manifest_sha256,
        "test_id": row["test_id"],
        "variant_id": row["variant_id"],
        "run_gate": row["run_gate"],
        "owner_tasks_sha256": content_hash(list(row["owner_tasks"])),
        "fixture_ref": row["fixture_ref"],
        "fixture_sha256": row["fixture_sha256"],
        "oracle_id": row["oracle_id"],
        "oracle_sha256": row["oracle_sha256"],
        "manifest_row_sha256": content_hash(row),
        "authority_coverage": coverage,
        "rebuild": rebuild_evidence,
        "implementation_sha": implementation_sha,
        "implementation_paths": implementation_paths,
        "environment": environment,
        "environment_digest": content_hash(environment),
        "status": "REBUILT",
        "recorded_at": recorded_at,
    }


def _implementation_paths() -> list[str]:
    return [
        "docs/dal/build_contract_manifests.py",
        "docs/dal/dal_jcs.py",
        "docs/dal/verify_transition_oracle_authority.py",
        "docs/dal/verify_operation_oracle_authority.py",
        "docs/dal/verify_test_manifest_authority.py",
        "docs/dal/verify_eval_schema_authority.py",
        "scripts/generate_dal_wave3_artifact_receipts.py",
        "scripts/verify_dal_artifact_receipts.py",
        "tests/dal/contract_loader.py",
    ]


def _wave3_variants(contracts: FrozenContracts) -> list:
    selected = []
    for test_id, variant_id in WAVE3_VARIANTS:
        for variant in contracts.variants(test_id):
            if variant.variant_id == variant_id:
                selected.append(variant)
                break
        else:
            raise ValueError(f"Wave 3 variant missing from frozen manifest: {test_id}/{variant_id}")
    if len(selected) != len(WAVE3_VARIANTS):
        raise ValueError(
            f"expected {len(WAVE3_VARIANTS)} Wave 3 variants, bound {len(selected)}"
        )
    return selected


def generate(write: bool = True) -> list[dict[str, Any]]:
    """Snapshot, rebuild, verify zero drift, then build all 14 receipts."""
    snapshot = _snapshot_manifest_files()
    _run_rebuild()
    _assert_zero_drift(snapshot)

    contracts = FrozenContracts()
    manifest = _load(MANIFESTS_DIR / "test-manifest_v1.2.json")
    manifest_sha256 = manifest["manifest_sha256"]

    implementation_sha = _git("rev-parse", "HEAD")
    recorded_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    rebuild_evidence = {
        "generator": GENERATOR,
        "scope_files": len(REBUILD_SCOPE),
        "drift": "none",
        "authorities_verified": [
            "transition-oracle-authority_v1.0.json",
            "operation-oracle-authority_v1.0.json",
            "test-manifest-authority_v1.0.json",
            "eval-schema-authority_v1.0.json",
        ],
    }

    receipts = []
    for variant in _wave3_variants(contracts):
        row = _frozen_row(manifest, variant)
        receipt = _build_receipt(
            row,
            manifest_sha256=manifest_sha256,
            rebuild_evidence=rebuild_evidence,
            implementation_sha=implementation_sha,
            implementation_paths=_implementation_paths(),
            recorded_at=recorded_at,
        )
        _assert_receipt_consistent(receipt, manifest, contracts, variant)
        receipts.append(receipt)

    if write:
        RECEIPTS_DIR.mkdir(parents=True, exist_ok=True)
        for receipt in receipts:
            path = _receipt_path(receipt)
            path.write_text(
                json.dumps(receipt, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
                encoding="utf-8",
            )
    return receipts


def _receipt_path(receipt: dict[str, Any]) -> Path:
    return (
        RECEIPTS_DIR
        / f"{receipt['test_id']}__{receipt['variant_id']}__{receipt['run_gate']}.json"
    )


def _frozen_row(manifest: dict, variant) -> dict[str, Any]:
    """Locate the exact frozen manifest row for this bound variant."""
    row = next(
        (
            row
            for row in manifest["test_variants"]
            if row["test_id"] == variant.test_id
            and row["variant_id"] == variant.variant_id
        ),
        None,
    )
    if row is None:
        raise ValueError(
            f"bound variant has no frozen manifest row: {variant.test_id}/{variant.variant_id}"
        )
    return row


def _assert_receipt_consistent(
    receipt: dict[str, Any],
    manifest: dict,
    contracts: FrozenContracts,
    variant,
) -> None:
    """Receipt must agree with the frozen row AND the recomputed binding.

    The receipt copies the row verbatim, so the row comparison alone would be
    a tautology. The independent evidence here is the contract loader's own
    hash-verified binding: it re-reads the fixture/oracle catalogs and fails
    closed on catalog drift, so agreement means the frozen row, the catalogs
    and this receipt all describe the same variant.
    """
    row = _frozen_row(manifest, variant)
    row_mismatches = [
        field
        for field in ("run_gate", "fixture_ref", "fixture_sha256", "oracle_id", "oracle_sha256")
        if receipt[field] != row[field]
    ]
    binding_mismatches: list[str] = []
    if receipt["run_gate"] != variant.run_gate:
        binding_mismatches.append("run_gate")
    if receipt["fixture_ref"] != variant.fixture.ref:
        binding_mismatches.append("fixture_ref")
    if receipt["fixture_sha256"] != content_hash(variant.fixture.body):
        binding_mismatches.append("fixture_sha256")
    if receipt["oracle_id"] != variant.oracle.oracle_id:
        binding_mismatches.append("oracle_id")
    if receipt["oracle_sha256"] != content_hash(variant.oracle.body):
        binding_mismatches.append("oracle_sha256")
    if receipt["owner_tasks_sha256"] != content_hash(list(variant.owner_tasks)):
        binding_mismatches.append("owner_tasks_sha256")
    if row_mismatches or binding_mismatches:
        raise ValueError(
            "receipt disagrees with the frozen contract set; refusing to write: "
            f"row={row_mismatches} binding={binding_mismatches} "
            f"({receipt['test_id']}/{receipt['variant_id']})"
        )
    coverage = receipt["authority_coverage"]
    if coverage["transition_oracle_authority"] == coverage["operation_oracle_authority"]:
        raise ValueError(
            "oracle must belong to exactly one of the two oracle authorities: "
            f"{receipt['test_id']}/{receipt['variant_id']} "
            f"(transition={coverage['transition_oracle_authority']}, "
            f"operation={coverage['operation_oracle_authority']})"
        )
    if not (
        coverage["test_manifest_authority"]
        and coverage["test_manifest_row_present"]
        and coverage["fixture_catalog_entry_present"]
    ):
        raise ValueError(
            "authority coverage incomplete for "
            f"{receipt['test_id']}/{receipt['variant_id']}; refusing to write"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="run the full snapshot/rebuild/verify pipeline but write nothing",
    )
    args = parser.parse_args(argv)

    try:
        receipts = generate(write=not args.dry_run)
    except (OSError, RuntimeError, ValueError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1

    print(
        json.dumps(
            {
                "schema_version": RECEIPT_SCHEMA,
                "receipts": len(receipts),
                "written": not args.dry_run,
                "status": "REBUILT",
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
