"""SQLite primitives shared by both service databases.

The Agent API and Finance MCP keep separate databases under separate service
users, but they must not disagree about how a timestamp is stored, what a sealed
column looks like, or which PRAGMAs are on. Two copies of that would drift, so
the column types and the engine setup live here and the models live per service.

Two PRAGMAs are load-bearing and easy to lose. `foreign_keys` is OFF in SQLite
unless set per connection, which leaves declared foreign keys as decoration.
`journal_mode=WAL` is persistent in the file but is set here so a freshly created
database gets it without a manual step.
"""

from __future__ import annotations

import base64
import binascii
import json
import time
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Any, Final, TypeVar

from sqlalchemy import Engine, MetaData, Text, TypeDecorator, create_engine, event, text
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import Session, sessionmaker

from personal_agent_core.timeutil import parse_rfc3339, to_rfc3339


T = TypeVar("T")

BUSY_TIMEOUT_MS: Final[int] = 5_000

#: Fixed so autogenerated migrations stay reviewable: constraint names that
#: shift between runs make a rollback diff impossible to read.
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}


class DatabaseIntegrityError(RuntimeError):
    """The database failed `PRAGMA integrity_check`."""


class UtcTimestamp(TypeDecorator[datetime]):
    """An aware UTC instant stored as RFC 3339 text.

    Text keeps backups and restore drills readable without a driver, and sorts
    correctly because every value is normalised to UTC with a `Z` suffix. Naive
    datetimes are rejected rather than assumed to be local time.
    """

    impl = Text
    cache_ok = True

    def process_bind_param(
        self, value: datetime | None, dialect: Any
    ) -> str | None:
        if value is None:
            return None
        return to_rfc3339(value)

    def process_result_value(
        self, value: str | None, dialect: Any
    ) -> datetime | None:
        if value is None:
            return None
        return parse_rfc3339(value)


class EncryptedEnvelope(TypeDecorator[dict[str, Any]]):
    """An AES-256-GCM envelope, per technical design 8.5.

    DEV-007 owns the cipher. This type owns the shape, and refuses anything that
    is not a sealed envelope, so a column named `encrypted_*` cannot end up
    holding plaintext while the crypto layer is still being built.
    """

    impl = Text
    cache_ok = True

    REQUIRED_KEYS = frozenset({"v", "kid", "nonce", "ciphertext", "tag"})

    @classmethod
    def _decode_base64url(cls, field: str, value: object) -> bytes:
        if not isinstance(value, str):
            raise ValueError(f"envelope {field} must be a base64url string")
        padding = "=" * (-len(value) % 4)
        try:
            return base64.b64decode(
                value + padding, altchars=b"-_", validate=True
            )
        except (binascii.Error, ValueError) as exc:
            raise ValueError(
                f"envelope {field} must be valid unpadded base64url"
            ) from exc

    @classmethod
    def _validate(cls, value: object) -> dict[str, Any]:
        if not isinstance(value, dict):
            raise ValueError(
                "encrypted columns take a sealed envelope, not a plain value"
            )
        keys = frozenset(value)
        missing = cls.REQUIRED_KEYS - keys
        extra = keys - cls.REQUIRED_KEYS
        if missing or extra:
            details = []
            if missing:
                details.append(f"missing {sorted(missing)}")
            if extra:
                details.append(f"unexpected {sorted(extra)}")
            raise ValueError(
                f"invalid encrypted envelope ({'; '.join(details)}); "
                "refusing to store anything outside the sealed shape"
            )

        version = value["v"]
        if not isinstance(version, int) or isinstance(version, bool) or version < 1:
            raise ValueError("envelope v must be a positive integer")
        kid = value["kid"]
        if not isinstance(kid, str) or not kid:
            raise ValueError("envelope kid must be a non-empty string")

        nonce = cls._decode_base64url("nonce", value["nonce"])
        cls._decode_base64url("ciphertext", value["ciphertext"])
        tag = cls._decode_base64url("tag", value["tag"])
        if len(nonce) != 12:
            raise ValueError("envelope nonce must decode to 12 bytes")
        if len(tag) != 16:
            raise ValueError("envelope tag must decode to 16 bytes")
        return value

    def process_bind_param(
        self, value: dict[str, Any] | None, dialect: Any
    ) -> str | None:
        if value is None:
            return None
        validated = self._validate(value)
        return json.dumps(validated, ensure_ascii=False, sort_keys=True)

    def process_result_value(
        self, value: str | None, dialect: Any
    ) -> dict[str, Any] | None:
        if value is None:
            return None
        return self._validate(json.loads(value))


def _configure_connection(dbapi_connection: Any, _record: Any) -> None:
    # pysqlite opens a transaction before DML but *not* before `SAVEPOINT`, so
    # with its own transaction handling a released `begin_nested()` block is
    # committed on the spot and `Session.rollback()` cannot undo it. Handing
    # transaction control to SQLAlchemy -- this line plus the explicit `BEGIN`
    # below -- is what makes a savepoint a savepoint and a rollback a rollback.
    dbapi_connection.isolation_level = None
    cursor = dbapi_connection.cursor()
    try:
        cursor.execute("PRAGMA journal_mode=WAL")
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.execute(f"PRAGMA busy_timeout={BUSY_TIMEOUT_MS}")
        cursor.execute("PRAGMA synchronous=FULL")
    finally:
        cursor.close()


def _begin_transaction(connection: Any) -> None:
    """Emit the `BEGIN` that pysqlite no longer emits once we own transactions."""
    connection.exec_driver_sql("BEGIN")


def create_database_engine(path: Path | str, *, echo: bool = False) -> Engine:
    """Build an engine with the required PRAGMAs and real transaction control.

    The two listeners are a pair: disabling pysqlite's implicit `BEGIN` without
    emitting one would leave every statement in autocommit. Both services share
    this because they must not disagree about what a transaction is.
    """
    engine = create_engine(f"sqlite+pysqlite:///{path}", echo=echo, future=True)
    event.listen(engine, "connect", _configure_connection)
    event.listen(engine, "begin", _begin_transaction)
    return engine


def _configure_read_only_connection(dbapi_connection: Any, _record: Any) -> None:
    """Configure a connection that must never mutate the restored file."""
    cursor = dbapi_connection.cursor()
    try:
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.execute("PRAGMA query_only=ON")
        cursor.execute(f"PRAGMA busy_timeout={BUSY_TIMEOUT_MS}")
    finally:
        cursor.close()


def create_read_only_database_engine(
    path: Path | str, *, echo: bool = False
) -> Engine:
    """Open an existing SQLite database with OS- and SQLite-level write refusal.

    Restore verification and read-only service smoke must not use
    :func:`create_database_engine`: its production connection hook deliberately
    sets ``journal_mode=WAL``, which may update the file and create sidecars.
    This engine opens ``mode=ro`` and also enables ``query_only`` so an accidental
    write fails at the database boundary instead of relying on caller discipline.
    """
    import sqlite3
    from urllib.parse import quote

    database = Path(path).resolve()
    if not database.is_file():
        raise FileNotFoundError(f"database does not exist: {database}")
    uri = f"file:{quote(database.as_posix(), safe='/')}?mode=ro"

    def connect():
        return sqlite3.connect(uri, uri=True, check_same_thread=False)

    engine = create_engine(
        "sqlite+pysqlite://",
        creator=connect,
        echo=echo,
        future=True,
    )
    event.listen(engine, "connect", _configure_read_only_connection)
    return engine


#: SQLite's answer when a transaction that already read tries to write after
#: someone else committed: the snapshot it holds can no longer be upgraded. WAL
#: reports it immediately -- `busy_timeout` does not apply, because waiting
#: cannot help -- so the only correct response is to end the transaction and run
#: the whole unit of work again against fresh state.
_SNAPSHOT_CONFLICT_MARKERS: Final[tuple[str, ...]] = (
    "database is locked",
    "database table is locked",
)


def is_snapshot_conflict(error: BaseException) -> bool:
    """Whether this error means "your read snapshot is stale; start over"."""
    if not isinstance(error, OperationalError):
        return False
    return any(
        marker in str(error.orig).lower() for marker in _SNAPSHOT_CONFLICT_MARKERS
    )


def run_write_transaction(
    session: Session,
    work: Callable[[], T],
    *,
    attempts: int = 3,
    retry_delay_seconds: float = 0.01,
) -> T:
    """Run one unit of database work, retrying a lost read snapshot.

    Only for work with **no external side effects**: it is called again from
    the start, so a unit that may have written to Feishu, asked a model or
    dispatched an MCP call must not be wrapped here. An idempotent read of our
    own control plane is safe, at the cost of repeating it. Every mutation in
    both services is a compare-and-swap guarded by `state_version` or a unique
    constraint, so a retry re-reads the current row and either proceeds
    correctly or reports the same conflict it would have reported without the
    race.
    """
    if attempts < 1:
        raise ValueError("attempts must be positive")
    if retry_delay_seconds < 0:
        raise ValueError("retry_delay_seconds must be non-negative")
    for remaining in range(attempts - 1, -1, -1):
        try:
            result = work()
            session.commit()
            return result
        except Exception as error:
            session.rollback()
            if remaining and is_snapshot_conflict(error):
                # The session is clean again; the next attempt begins a new
                # transaction and therefore reads a fresh snapshot. A different
                # writer may still be active, so immediate tight-loop retries
                # can exhaust before it commits; use a short bounded backoff.
                completed_attempts = attempts - remaining
                time.sleep(
                    min(
                        retry_delay_seconds * (2 ** (completed_attempts - 1)),
                        0.1,
                    )
                )
                continue
            raise
    raise AssertionError("unreachable")  # pragma: no cover


def check_integrity(engine: Engine) -> None:
    """Raise unless SQLite reports the database as intact.

    Technical design 10.4: if idempotency or audit state cannot be trusted,
    write tools fail closed. So this raises rather than warns.
    """
    with engine.connect() as connection:
        result = connection.execute(text("PRAGMA integrity_check")).scalar_one()
    if result != "ok":
        raise DatabaseIntegrityError(
            f"integrity_check did not return ok: {result!r}"
        )


class BackupError(RuntimeError):
    """An online backup could not be produced or did not verify."""


class BackupUnavailableError(BackupError):
    """The source database could not be opened or read at all.

    Distinct from :class:`BackupError` so a caller can map "I could not make a
    snapshot" (exit 2 in the observe_cli contract) apart from "I made a snapshot
    and it failed integrity" (exit 1). Collapsing them lets an unreachable
    source look like a bad snapshot, which is the wrong diagnosis.
    """


def _integrity_check(path: Path) -> str:
    """Open ``path`` read-only and return its ``integrity_check`` result.

    A fresh connection on the *destination* file, never the live source. Pulled
    out so the post-copy verification can be exercised independently of the
    backup API: a snapshot that completes can still be corrupt on a flaky disk,
    and the check is what stops restic from shipping corruption offsite.
    """
    import sqlite3

    conn = sqlite3.connect(f"file:{Path(path).as_posix()}?mode=ro", uri=True)
    try:
        row = conn.execute("PRAGMA integrity_check").fetchone()
    except sqlite3.Error as exc:
        # A snapshot so corrupt it cannot be opened, or whose schema is
        # unreadable, is not "ok". `integrity_check` normally returns a text
        # diagnosis for corruption; this is the worse case where the file will
        # not even run the pragma. Treat it as a failed check.
        return f"unreadable: {exc}"
    finally:
        conn.close()
    return row[0] if row else ""


#: Default snapshot mode: owner-only. A snapshot of a 0600 service database is
#: exactly as sensitive as the database, so widening is opt-in and per-call.
SNAPSHOT_MODE: Final[int] = 0o600

#: The mode a snapshot needs when it is staged for the offsite backup user. The
#: staging directory is 2770 root-of-service:personal-agent-backup with no
#: 'other' bits, so 0640 shares the file with that one group and nobody else.
STAGED_SNAPSHOT_MODE: Final[int] = 0o640


def online_backup(
    source: Path | str,
    destination: Path,
    *,
    busy_timeout_ms: int = BUSY_TIMEOUT_MS,
    mode: int = SNAPSHOT_MODE,
    _verify: Callable[[Path], str] = _integrity_check,
) -> Path:
    """Copy a live SQLite database into a consistent snapshot file.

    Technical design 10.5: snapshots must come from the Online Backup API, not
    a raw file copy. A running WAL-mode database's main file can be mid-checkpoint,
    so ``cp`` may capture a half-written page; ``Connection.backup()`` reads
    through the source's own pager and is safe to run while the service writes.

    The source is opened read-only (``?mode=ro``), so a backup process can never
    mutate the live database. The destination is written to a temporary sibling
    and ``os.replace``\\ d into place, so an interrupted run leaves no half-file
    that a later step could mistake for a good snapshot. After the copy, a fresh
    connection runs ``PRAGMA integrity_check`` *on the destination*; anything
    other than ``ok`` is deleted and raised as :class:`BackupError` -- a corrupt
    snapshot is worse than no snapshot, because restic would faithfully encrypt
    and ship the corruption offsite.

    ``mode`` is applied to the finished file explicitly, so the result never
    depends on the caller's umask. It defaults to owner-only; a caller staging
    the snapshot for the offsite backup user passes
    :data:`STAGED_SNAPSHOT_MODE`, which is the only widening in the system and
    is readable only to the staging directory's group.

    Returns the destination path on success.
    """
    import os
    import sqlite3
    import tempfile

    source_path = Path(source)
    if not source_path.exists():
        raise BackupUnavailableError(
            f"source database does not exist: {source_path}"
        )
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)

    # Read-only source: a backup process has no business writing the live DB.
    source_uri = f"file:{source_path.as_posix()}?mode=ro"
    try:
        src_conn = sqlite3.connect(source_uri, uri=True, timeout=busy_timeout_ms / 1000)
    except sqlite3.Error as exc:
        raise BackupUnavailableError(
            f"could not open source database read-only: {exc}"
        ) from exc

    tmp_fd, tmp_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=str(destination.parent)
    )
    os.close(tmp_fd)
    tmp_path = Path(tmp_name)
    # The temp file is created world-readable by mkstemp; a snapshot of a
    # 0600 service database must not leak through a backup staging directory.
    # The half-written file is always owner-only, whatever the final mode is:
    # nothing may read a snapshot that has not passed integrity_check yet.
    os.chmod(tmp_path, SNAPSHOT_MODE)

    try:
        # A fresh destination connection owns its own file; opening it before the
        # backup would create an empty DB the API would then overwrite page by page.
        dst_conn = sqlite3.connect(str(tmp_path))
        try:
            try:
                src_conn.backup(dst_conn)
            finally:
                dst_conn.close()
                src_conn.close()
        except sqlite3.Error as exc:
            raise BackupError(f"online backup failed: {exc}") from exc

        # Verify the snapshot, not the source. A copy that completed can still be
        # corrupt if the source was mid-checkpoint in a way the API could not
        # reconcile, and restic will happily encrypt corruption.
        result = _verify(tmp_path)
        if result != "ok":
            raise BackupError(
                f"destination failed integrity_check: {result!r}"
            )

        os.replace(tmp_path, destination)
        # os.replace inherits the temp's mode; set the requested one explicitly
        # so neither a umask nor a pre-existing destination decides it.
        os.chmod(destination, mode)
        return destination
    finally:
        # The destination connection is WAL-capable, so sqlite may have created
        # `<tmp>-shm` / `<tmp>-wal` siblings. os.replace moves only the main
        # file, so without this every run leaves two orphans behind in the
        # staging directory -- observed accumulating there on 2026-08-01.
        # `unlink` on the temp itself is a no-op after a successful replace and
        # the cleanup an error path needs: a half-written snapshot must never
        # linger where a later step could mistake it for a good one.
        for orphan in (tmp_path, Path(f"{tmp_path}-shm"), Path(f"{tmp_path}-wal")):
            orphan.unlink(missing_ok=True)


def session_factory(engine: Engine) -> sessionmaker[Session]:
    return sessionmaker(bind=engine, expire_on_commit=False, future=True)


def create_all(engine: Engine, metadata: MetaData) -> None:
    """Create a schema directly.

    For tests and throwaway fixtures only. Deployed databases are built and
    moved forward by Alembic so every change has a reviewable, reversible
    migration.
    """
    metadata.create_all(engine)
