"""SQLite primitives shared by both service databases.

The Agent API and Finance MCP keep separate databases under separate service
users, but they must not disagree about how a timestamp is stored, what a sealed
column looks like, or which PRAGMAs are on. Two copies of that would drift, so
the column types and the engine setup live here and the models live per service.

Two PRAGMAs are load-bearing and easy to lose. `foreign_keys` is OFF in SQLite
unless set per connection, which leaves declared foreign keys as decoration.
`journal_mode=WAL` is persistent in the file but is set here so a freshly created
database gets it without a manual step.
"""

from __future__ import annotations

import base64
import binascii
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Final

from sqlalchemy import Engine, MetaData, Text, TypeDecorator, create_engine, event, text
from sqlalchemy.orm import Session, sessionmaker

from personal_agent_core.timeutil import parse_rfc3339, to_rfc3339


BUSY_TIMEOUT_MS: Final[int] = 5_000

#: Fixed so autogenerated migrations stay reviewable: constraint names that
#: shift between runs make a rollback diff impossible to read.
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}


class DatabaseIntegrityError(RuntimeError):
    """The database failed `PRAGMA integrity_check`."""


class UtcTimestamp(TypeDecorator[datetime]):
    """An aware UTC instant stored as RFC 3339 text.

    Text keeps backups and restore drills readable without a driver, and sorts
    correctly because every value is normalised to UTC with a `Z` suffix. Naive
    datetimes are rejected rather than assumed to be local time.
    """

    impl = Text
    cache_ok = True

    def process_bind_param(
        self, value: datetime | None, dialect: Any
    ) -> str | None:
        if value is None:
            return None
        return to_rfc3339(value)

    def process_result_value(
        self, value: str | None, dialect: Any
    ) -> datetime | None:
        if value is None:
            return None
        return parse_rfc3339(value)


class EncryptedEnvelope(TypeDecorator[dict[str, Any]]):
    """An AES-256-GCM envelope, per technical design 8.5.

    DEV-007 owns the cipher. This type owns the shape, and refuses anything that
    is not a sealed envelope, so a column named `encrypted_*` cannot end up
    holding plaintext while the crypto layer is still being built.
    """

    impl = Text
    cache_ok = True

    REQUIRED_KEYS = frozenset({"v", "kid", "nonce", "ciphertext", "tag"})

    @classmethod
    def _decode_base64url(cls, field: str, value: object) -> bytes:
        if not isinstance(value, str):
            raise ValueError(f"envelope {field} must be a base64url string")
        padding = "=" * (-len(value) % 4)
        try:
            return base64.b64decode(
                value + padding, altchars=b"-_", validate=True
            )
        except (binascii.Error, ValueError) as exc:
            raise ValueError(
                f"envelope {field} must be valid unpadded base64url"
            ) from exc

    @classmethod
    def _validate(cls, value: object) -> dict[str, Any]:
        if not isinstance(value, dict):
            raise ValueError(
                "encrypted columns take a sealed envelope, not a plain value"
            )
        keys = frozenset(value)
        missing = cls.REQUIRED_KEYS - keys
        extra = keys - cls.REQUIRED_KEYS
        if missing or extra:
            details = []
            if missing:
                details.append(f"missing {sorted(missing)}")
            if extra:
                details.append(f"unexpected {sorted(extra)}")
            raise ValueError(
                f"invalid encrypted envelope ({'; '.join(details)}); "
                "refusing to store anything outside the sealed shape"
            )

        version = value["v"]
        if not isinstance(version, int) or isinstance(version, bool) or version < 1:
            raise ValueError("envelope v must be a positive integer")
        kid = value["kid"]
        if not isinstance(kid, str) or not kid:
            raise ValueError("envelope kid must be a non-empty string")

        nonce = cls._decode_base64url("nonce", value["nonce"])
        cls._decode_base64url("ciphertext", value["ciphertext"])
        tag = cls._decode_base64url("tag", value["tag"])
        if len(nonce) != 12:
            raise ValueError("envelope nonce must decode to 12 bytes")
        if len(tag) != 16:
            raise ValueError("envelope tag must decode to 16 bytes")
        return value

    def process_bind_param(
        self, value: dict[str, Any] | None, dialect: Any
    ) -> str | None:
        if value is None:
            return None
        validated = self._validate(value)
        return json.dumps(validated, ensure_ascii=False, sort_keys=True)

    def process_result_value(
        self, value: str | None, dialect: Any
    ) -> dict[str, Any] | None:
        if value is None:
            return None
        return self._validate(json.loads(value))


def _configure_connection(dbapi_connection: Any, _record: Any) -> None:
    cursor = dbapi_connection.cursor()
    try:
        cursor.execute("PRAGMA journal_mode=WAL")
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.execute(f"PRAGMA busy_timeout={BUSY_TIMEOUT_MS}")
        cursor.execute("PRAGMA synchronous=FULL")
    finally:
        cursor.close()


def create_database_engine(path: Path | str, *, echo: bool = False) -> Engine:
    """Build an engine with the required PRAGMAs applied to every connection."""
    engine = create_engine(f"sqlite+pysqlite:///{path}", echo=echo, future=True)
    event.listen(engine, "connect", _configure_connection)
    return engine


def check_integrity(engine: Engine) -> None:
    """Raise unless SQLite reports the database as intact.

    Technical design 10.4: if idempotency or audit state cannot be trusted,
    write tools fail closed. So this raises rather than warns.
    """
    with engine.connect() as connection:
        result = connection.execute(text("PRAGMA integrity_check")).scalar_one()
    if result != "ok":
        raise DatabaseIntegrityError(
            f"integrity_check did not return ok: {result!r}"
        )


def session_factory(engine: Engine) -> sessionmaker[Session]:
    return sessionmaker(bind=engine, expire_on_commit=False, future=True)


def create_all(engine: Engine, metadata: MetaData) -> None:
    """Create a schema directly.

    For tests and throwaway fixtures only. Deployed databases are built and
    moved forward by Alembic so every change has a reviewable, reversible
    migration.
    """
    metadata.create_all(engine)
